### ISSUE TITLE
Where To Set User Credentials?

### ISSUE THREAD

**Issue by ahmadawais** [rmccue/not-trac#6]
So, I gave it a try and ended up with.

```json
{
"message": "Username and password are required",
"error": true
}
```

Added user cred to `login.js` file but nothing changed? Haven't had time to dig in the code yet —  can you share where to set the user cred?

**Comment by OriginalEXE** [comment]
I have not used this yet but I notice there's a Login component in the components folder so it looks like there should be a screen within the app where you log in, you shouldn't have to hardcode the credentials.

**Comment by rmccue** [comment]
Indeed, when you run the app, it should show you a login screen. (Your username/password are then stored in local storage.)

**Comment by ahmadawais** [comment]
OK! I can see this issue. The instructions are missing the script name.
